import styles from './page.module.css';
import { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'Blogs | Travel Blog',
  description: 'Generated by create next app',
};

export default function page() {
  return (
    <>
      <h1>Blog Posts</h1>
    </>
  );
}
