import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from '@/components/navigation/navbar';
export const metadata = {
  title: 'Home | Travel Blog',
  description: 'Generated by create next app',
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='container'>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
