import { Metadata } from 'next';
import styles from './blog-route.module.css';
import placesData from '@/data/places.json';
import ImageComponent from '@/components/image/ImageComponent';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Blogs | Travel Blog',
  description: 'Generated by create next app',
};

export default function page() {
  return (
    <>
      <h1 className={styles.title}>Blog posts</h1>
      {placesData.places.map((place, index) => {
        return (
          <>
            <Link className={styles.link} key={index} href={`/blog/${index}`}>
              <div
                style={{
                  position: 'relative',
                  width: '100%',
                  height: '500px',
                  marginTop: '2rem',
                }}
              >
                <ImageComponent
                  className={styles.image}
                  src={place.photoUrl}
                  alt='/'
                />
              </div>
              <div className={styles.places}>
                <h1>{place.name}</h1>
                <p>{place.description}</p>
              </div>
            </Link>
          </>
        );
      })}
    </>
  );
}
